apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  # [식별] 서비스명과 팀 번호를 조합한 고유 클러스터 이름
  name: ${SERVICE_NAME}-team-${TEAM_NUMBER}-cluster
  region: ${AWS_REGION}
  version: "1.34"

vpc:
  # [기반] 1번 네트워크 스택에서 생성한 VPC ID 연동
  id: ${MY_VPC_ID}
  subnets:
    public:
      # [외부] 로드밸런서(ALB)가 배치될 퍼블릭 서브넷 (AZ 자동 매핑)
      - id: ${PUB_SUBNET_A}
      - id: ${PUB_SUBNET_B}
    private:
      # [내부] EKS 노드들이 배치될 보안 전용 App 프라이빗 서브넷
      - id: ${APP_PRI_SUBNET_A}
      - id: ${APP_PRI_SUBNET_B}

managedNodeGroups:
  - name: m7i-flex-large-nodes # [성능] 인스턴스 사양을 명시한 노드 그룹 이름
    instanceType: m7i-flex.large
    desiredCapacity: 2          # [가용성] 분석 작업을 위한 최소 노드 개수
    volumeSize: 20              # [저장소] 각 노드의 기본 디스크 용량 (GiB)
    privateNetworking: true     # [보안] 노드에 공인 IP를 부여하지 않고 내부에 숨김
    iam:
      withAddonPolicies:
        imageBuilder: true      # ECR 이미지 빌드 권한
        albIngress: true        # ALB 컨트롤러가 로드밸런서를 생성할 권한
        cloudWatch: true        # 로그 및 메트릭 전송 권한
        autoScaler: true        # 트래픽에 따른 노드 자동 확장 권한

cloudWatch:
  clusterLogging:
    # [관제] 모든 클러스터 제어부 로그를 수집하여 분석 가능하게 설정 [cite: 2026-01-23]
    enableTypes: ["*"]
